#!/usr/bin/env python3
"""Generate TradingView alert packs for Kim Paper Broker.

This avoids trying to control TradingView Paper Trading directly. It creates a
Pine Script that watches all pending Kim paper orders and sends webhook JSON
back to Kim when a level is touched.
"""

from __future__ import annotations

import argparse
import json
import pathlib
from datetime import datetime, timezone


BIFROST = pathlib.Path("/Users/dryehoshuapython/Documents/BIFROST")
RUNTIME = pathlib.Path("/Users/dryehoshuapython/.kim_live")
PAPER_DIR = BIFROST / "MEMORY" / "portfolios" / "ignis_stock_financials" / "clientes" / "manejo_de_portafolios" / "sr_eli_2026" / "paper_trading"
PAPER_ORDERS = PAPER_DIR / "paper_orders.json"
WEBHOOK_CONFIG = BIFROST / "MEMORY" / "context" / "tradingview_webhook.json"
RUNTIME_WEBHOOK_CONFIG = RUNTIME / "context" / "tradingview_webhook.json"
OUTPUT_DIR = PAPER_DIR / "tradingview_alerts"
WEBHOOK_URL = "https://kim.aipeople.app/api/tradingview/webhook"


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def read_json(path: pathlib.Path, default):
    try:
        if path.exists():
            return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        pass
    return default


def write_json(path: pathlib.Path, payload) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def tradingview_symbol(symbol: str, exchange: str = "BINANCE") -> str:
    token = str(symbol or "").upper().strip().replace(" ", "")
    if ":" in token:
        return token
    return f"{exchange}:{token}"


def pine_string(value: str) -> str:
    return str(value or "").replace("\\", "\\\\").replace('"', '\\"')


def load_token() -> str:
    config = read_json(WEBHOOK_CONFIG, None)
    if not isinstance(config, dict):
        config = read_json(RUNTIME_WEBHOOK_CONFIG, {})
    token = str((config or {}).get("token") or "").strip()
    if not token:
        raise SystemExit("Missing TradingView webhook token. Open Kim Paper Broker once to generate it.")
    return token


def load_pending_orders(exchange: str = "BINANCE") -> list[dict]:
    data = read_json(PAPER_ORDERS, {})
    orders = []
    for order in data.get("orders") or []:
        if not isinstance(order, dict) or order.get("status") != "pending":
            continue
        side = str(order.get("side") or "BUY").upper()
        if side not in {"BUY", "SELL"}:
            continue
        limit_price = order.get("limit_price")
        try:
            limit = float(limit_price)
        except (TypeError, ValueError):
            continue
        symbol = str(order.get("symbol") or "").upper().strip()
        if not symbol:
            continue
        orders.append(
            {
                "order_id": order.get("order_id") or "",
                "source_portfolio_pending_id": order.get("source_portfolio_pending_id") or "",
                "symbol": symbol,
                "tradingview_symbol": tradingview_symbol(symbol, exchange=exchange),
                "side": side,
                "limit_price": limit,
                "amount_usd": order.get("amount_usd"),
                "notes": order.get("notes") or "",
            }
        )
    return orders


def alert_payload_template(token: str, order: dict, price_expr: str) -> str:
    # Pine concatenates dynamic price while the rest of the payload stays stable.
    static_prefix = (
        '{"token":"' + token + '",'
        '"source":"tradingview_pine_alert",'
        '"portfolio_id":"sr_eli_2026",'
        f'"order_id":"{pine_string(order["order_id"])}",'
        f'"symbol":"{pine_string(order["symbol"])}",'
        f'"side":"{pine_string(order["side"])}",'
        f'"limit_price":{order["limit_price"]},'
        '"price":'
    )
    static_suffix = ',"message":"Kim paper order level touched"}'
    return f'"{pine_string(static_prefix)}" + str.tostring({price_expr}) + "{pine_string(static_suffix)}"'


def generate_pine(orders: list[dict], token: str) -> str:
    lines = [
        "//@version=5",
        'indicator("Kim Sr Eli Paper Broker Alerts", overlay=false, max_labels_count=100)',
        "// Generated by BIFROST kimtools/tradingview_alert_bridge.py",
        f"// Generated at {utc_now_iso()}",
        "// Create ONE TradingView alert using: Any alert() function call.",
        "",
    ]
    for index, order in enumerate(orders, start=1):
        name = f"o{index}"
        symbol = pine_string(order["tradingview_symbol"])
        side = order["side"]
        op = "<=" if side == "BUY" else ">="
        lines.extend(
            [
                f'{name}_price = request.security("{symbol}", timeframe.period, close)',
                f"{name}_hit = {name}_price {op} {order['limit_price']}",
                f"if {name}_hit and not {name}_hit[1]",
                f"    alert({alert_payload_template(token, order, name + '_price')}, alert.freq_once_per_bar)",
                "",
            ]
        )
    if not orders:
        lines.append("// No pending orders found.")
    return "\n".join(lines)


def generate_alert_pack(exchange: str = "BINANCE") -> dict:
    token = load_token()
    orders = load_pending_orders(exchange=exchange)
    pine = generate_pine(orders, token)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = {
        "ok": True,
        "generated_at": utc_now_iso(),
        "mode": "single_pine_script_any_alert_function_call",
        "webhook_url": WEBHOOK_URL,
        "token_masked": token[:4] + "..." + token[-4:],
        "order_count": len(orders),
        "orders": orders,
        "instructions": [
            "Open TradingView Pine Editor.",
            "Paste the generated .pine script and add it to chart.",
            "Create one alert with condition: Kim Sr Eli Paper Broker Alerts / Any alert() function call.",
            f"Set Webhook URL to {WEBHOOK_URL}.",
            "The script alert() body already contains the JSON payload and Kim token.",
        ],
    }
    pine_path = OUTPUT_DIR / "kim_sr_eli_paper_alerts_latest.pine"
    manifest_path = OUTPUT_DIR / "kim_sr_eli_paper_alerts_manifest.json"
    redacted_path = OUTPUT_DIR / "kim_sr_eli_paper_alerts_redacted.pine"
    pine_path.write_text(pine, encoding="utf-8")
    redacted_path.write_text(pine.replace(token, "<KIM_WEBHOOK_TOKEN>"), encoding="utf-8")
    write_json(manifest_path, manifest)
    manifest["paths"] = {
        "pine_with_secret": str(pine_path),
        "pine_redacted": str(redacted_path),
        "manifest": str(manifest_path),
    }
    write_json(manifest_path, manifest)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Kim TradingView alert pack.")
    parser.add_argument("command", choices=["generate", "print"], nargs="?", default="generate")
    parser.add_argument("--exchange", default="BINANCE")
    args = parser.parse_args()
    manifest = generate_alert_pack(exchange=args.exchange)
    if args.command == "print":
        print(pathlib.Path(manifest["paths"]["pine_redacted"]).read_text(encoding="utf-8"))
    else:
        print(json.dumps({k: v for k, v in manifest.items() if k != "orders"}, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
